/**
 * Generated by tsnapi — public API snapshot of `is-private-ip`
 */
// #region Functions
export declare function isNonPublicIp(_: string): boolean;
export declare function isNonPublicIpv4(_: string): boolean;
export declare function isNonPublicIpv6(_: string): boolean;
export declare function isPrivateIp(_: string): boolean;
export declare function isPrivateIpv4(_: string): boolean;
export declare function isPrivateIpv6(_: string): boolean;
// #endregion
